###Get all devs

GET http://127.0.0.1:8000/dev

### add a dev

POST http://127.0.0.1:8000/dev/addDev
content-Type: application/json

{
    "github_username": "jarn40",
    "techs": "Mongo, Express, React, Node",
    "latitude":-12.9298496,
    "longitude":-38.4324061
}

### serch devs nearby and by tech

GET http://127.0.0.1:8000/dev/searchNearby
    ?latitude=-12.9298496
    &longitude=-38.4324061
    &techs=Django, Express

### remove

DELETE http://127.0.0.1:8000/dev/removeDev
content-Type: application/json

{
    "id":"5e4973bf1e71f540d48735d4"
}